# Generated by Django 2.2.24 on 2022-01-24 13:36

from django.db import migrations

def copy_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for real_estate_object in Flat.objects.all():
        Owner.objects.get_or_create(owner=real_estate_object.owner,
                    owners_phonenumber=real_estate_object.owners_phonenumber,
                    owner_pure_phone=real_estate_object.owner_pure_phone)

def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for real_estate_object in Flat.objects.all():
        Owner.objects.get_or_create(owner=real_estate_object.owner,
                    owners_phonenumber=real_estate_object.owners_phonenumber,
                    owner_pure_phone=real_estate_object.owner_pure_phone)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(copy_owners,
                             move_backward)
    ]
