# Generated by Django 2.2.24 on 2022-01-24 16:15

from django.db import migrations

from property.models import Flat


def create_link(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for real_estate_object in Flat.objects.all():
        record = Owner.objects.get_or_create(owner=real_estate_object.owner,
                    owners_phonenumber=real_estate_object.owners_phonenumber,
                    owner_pure_phone=real_estate_object.owner_pure_phone,)
        record[0].flats.add(real_estate_object)
                    

def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for real_estate_object in Flat.objects.all():
        record = Owner.objects.get_or_create(owner=real_estate_object.owner,
                    owners_phonenumber=real_estate_object.owners_phonenumber,
                    owner_pure_phone=real_estate_object.owner_pure_phone,)
        record[0].flats.add(real_estate_object)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20220124_1636'),
    ]

    operations = [
        migrations.RunPython(create_link,
                             move_backward)
    ]
