# Generated by Django 2.2.24 on 2022-01-26 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20220126_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сomplaint',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint', to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался'),
        ),
        migrations.AlterField(
            model_name='сomplaint',
            name='flat_complaint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint', to='property.Flat', verbose_name='Квартира,\n                                       на которую пожаловались'),
        ),
    ]
